# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video_stream.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'video_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12video_stream.proto\"7\n\x13VideoSegmentRequest\x12\x10\n\x08ms_start\x18\x01 \x01(\x04\x12\x0e\n\x06ms_end\x18\x02 \x01(\x04\"5\n\x14VideoSegmentResponse\x12\x0e\n\x06\x66ormat\x18\x01 \x01(\t\x12\r\n\x05\x63hunk\x18\x02 \x01(\x0c\x32H\n\x0bVideoStream\x12\x39\n\nGetSegment\x12\x14.VideoSegmentRequest\x1a\x15.VideoSegmentResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_VIDEOSEGMENTREQUEST']._serialized_start=22
  _globals['_VIDEOSEGMENTREQUEST']._serialized_end=77
  _globals['_VIDEOSEGMENTRESPONSE']._serialized_start=79
  _globals['_VIDEOSEGMENTRESPONSE']._serialized_end=132
  _globals['_VIDEOSTREAM']._serialized_start=134
  _globals['_VIDEOSTREAM']._serialized_end=206
# @@protoc_insertion_point(module_scope)
